[versions]
kotlin = "1.5.31"
compose = "1.0.5"
ktor = "1.6.5"

[libraries]
annotation = "androidx.annotation:annotation:1.2.0"
core = "androidx.core:core-ktx:1.6.0"
appcompat = "androidx.appcompat:appcompat:1.3.1"
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.1"
material = "com.google.android.material:material:1.4.0"
lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.3.1"
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.1"
coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.1"
ktor = { module = "io.ktor:ktor-network", version.ref = "ktor" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = "androidx.activity:activity-compose:1.3.1"

# test
junit = "junit:junit:4.13.2"
mockk = "io.mockk:mockk:1.12.0"
androidx-test = "androidx.test.ext:junit:1.1.3"
espresso = "androidx.test.espresso:espresso-core:3.4.0"
