name: Update gh-pages

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  update-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build docs
        run: ./gradlew dokkaHtml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./libreastream/build/dokka/html
